version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
      - "5556:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookly
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookly
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"
volumes:
  pgdata: