// This file is automatically generated and should not be edited.
// It provides type information for your SvelteKit routes.

declare module './$types' {
  export type Actions = import('@sveltejs/kit').Actions;
  export type Load = import('@sveltejs/kit').Load;
  export type ServerLoad = import('@sveltejs/kit').ServerLoad;
  export type RequestEvent = import('@sveltejs/kit').RequestEvent;
  export type RequestHandler = import('@sveltejs/kit').RequestHandler;
  export type PageServerLoad = import('@sveltejs/kit').PageServerLoad;
  export type Action = import('@sveltejs/kit').Action;
  export type ServerRequest = import('@sveltejs/kit').ServerRequest;
  export type ServerResponse = import('@sveltejs/kit').ServerResponse;
  export type Session = any; // Define your session type here if needed
  export type Locals = any; // Define your locals type here if needed
  export type PageData = any; // Define your page data type here if needed
  export type Error = any; // Define your error type here if needed
}
